services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker-compose-volumes/redis:/data
#    networks:
#      - pyw3

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_ALLOW_EMPTY_PASSWORD=true
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - "./docker-compose-volumes/mariadb:/var/lib/mysql"
      - "./docker-compose-volumes/entrypoint/bootstrap-tables.sql:/docker-entrypoint-initdb.d/init.sql"
#    networks:
#      - pyw3

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./docker-compose-volumes/mongodb:/data/db"
      - "./docker-compose-volumes/entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_MONGO_DATABASE}
#    networks:
#      - pyw3


#networks:
#  pyw3: { }
